spring:
  application:
    name: ne_template

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springboot_template_db
    username: pacifique
    password: myPassword123



  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


jwt:
  secretKey: "bbb2JvLuOKbhGcbf3iw3RP3Y1leWUouWU6mxAMZk0hmQwiwwjewj3e82u812q281wdpqu23usg"

server:
  port: 8844



springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
